parameters:
    lego.action.index.class: Idk\LegoBundle\Action\IndexAction
    lego.action.order_components.class: Idk\LegoBundle\Action\OrderComponentsAction
    lego.action.add.class: Idk\LegoBundle\Action\AddAction
    lego.action.export.class: Idk\LegoBundle\Action\ExportAction
    lego.action.show.class: Idk\LegoBundle\Action\ShowAction
    lego.action.editinplace.class: Idk\LegoBundle\Action\EditInPlaceAction
    lego.action.edit.class: Idk\LegoBundle\Action\EditAction
    lego.action.delete.class: Idk\LegoBundle\Action\DeleteAction
    lego.action.bulk.class: Idk\LegoBundle\Action\BulkAction
    lego.action.component.class: Idk\LegoBundle\Action\ComponentAction

services:

    _defaults:
        autowire: true
        public: false

    lego.action.index:
        class: '%lego.action.index.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.component:
        class: '%lego.action.component.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.bulk:
        class: '%lego.action.bulk.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.delete:
        class: '%lego.action.delete.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.edit:
        class: '%lego.action.edit.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.editinplace:
        class: '%lego.action.editinplace.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.show:
        class: '%lego.action.show.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.add:
        class: '%lego.action.add.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.export:
        class: '%lego.action.export.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]

    lego.action.order_components:
        class: '%lego.action.order_components.class%'
        arguments: ["@service_container","@lego.service.meta_entity_manager"]
        tags: [controller.service_arguments]