parameters:
    lego.component.filter.class: Idk\LegoBundle\Component\Filter
    lego.component.action.class: Idk\LegoBundle\Component\Action

services:

    _defaults:
        autowire: true
        public: false

    Idk\LegoBundle\Component\:
        shared: false
        resource: '../../Component'
        tags: [lego.component]


