parameters:
    lego.service.export.class: Idk\LegoBundle\Service\ExportService
    lego.service.menu: '@Idk\LegoBundle\Service\Menu'
    lego.service.header: '@Idk\LegoBundle\Service\Header'
    lego.service.footer: '@Idk\LegoBundle\Service\Footer'
    lego.service.meta_entity_manager.class: Idk\LegoBundle\Service\MetaEntityManager
    lego.service.gedmo_translatable_field_manager.class: Idk\LegoBundle\Service\GedmoTranslatableFieldManager
    lego.service.password_encoder.class: Idk\LegoBundle\Service\PasswordEncoder
    lego.widgets.template: 'IdkLegoBundle:Widget:replacer.html.twig'
    lego.widget.template: 'IdkLegoBundle:Widget:one_replacer.html.twig'

services:

    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Idk\LegoBundle\Command\:
         resource: '../../Command'

    Idk\LegoBundle\Controller\:
         resource: '../../Controller'

    Idk\LegoBundle\Service\Menu:
        arguments: ["@lego.service.meta_entity_manager", "@security.token_storage"]
    Idk\LegoBundle\Service\LegoMenuInterface: '@Idk\LegoBundle\Service\Menu'
    Idk\LegoBundle\Service\Header:
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
    Idk\LegoBundle\Service\LegoHeaderInterface: '@Idk\LegoBundle\Service\Header'
    Idk\LegoBundle\Service\Footer:
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
    Idk\LegoBundle\Service\LegoFooterInterface: '@Idk\LegoBundle\Service\Footer'
    lego.widget.chain:
        class: Idk\LegoBundle\Service\Tag\WidgetChain
        arguments: [!tagged lego.widget, '@session']

    lego.injector.chain:
        class: Idk\LegoBundle\Service\Tag\InjectorChain
        arguments: [!tagged lego.injector]

    Idk\LegoBundle\Maker\:
        resource: '../../Maker'
        arguments: ["@maker.file_manager","@lego.service.meta_entity_manager","@maker.doctrine_helper", "@lego.injector.chain"]
        tags: [maker.command]

    Idk\LegoBundle\Service\LegoInjector:
        tags: [lego.injector]


    lego.service.meta_entity_manager:
        class:  '%lego.service.meta_entity_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]
    Idk\LegoBundle\Service\MetaEntityManager: '@lego.service.meta_entity_manager'
    #Idk\LegoBundle\Service\MetaEntityManagerInterface: '@lego.service.meta_entity_manager'


    lego.service.gedmo_translatable_field_manager:
        class:  '%lego.service.gedmo_translatable_field_manager.class%'
        arguments: ["@doctrine"]

    Idk\LegoBundle\Service\GlobalsParametersProvider:
        class: Idk\LegoBundle\Service\GlobalsParametersProvider
        arguments: ["%lego.skin%","%lego.layout%", "%lego.layout_login%", "%lego.route.login%", "%lego.route.logout%", "%lego.user.class%"]

    lego.twig.extension:
        class: Idk\LegoBundle\Twig\LegoTwigExtension
        tags:
            -  { name: twig.extension  }

    lego.widget.twig.extension:
        class: Idk\LegoBundle\Twig\WidgetTwigExtension
        arguments: ["@lego.widget.chain","%lego.widgets.template%", "%lego.widget.template%"]
        tags:
            -  { name: twig.extension  }

    lego.listener.upload_file:
        class: Idk\LegoBundle\Listener\UploadFileListener
        arguments:    ["%kernel.project_dir%"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }


    lego.twig.filter:
        class: Idk\LegoBundle\Twig\FilterTwigExtension
        tags:
            -  { name: twig.extension }

    lego.service.csv:
        class:        Idk\LegoBundle\Service\CsvManager
        arguments:    ["@doctrine.orm.entity_manager",";",'"']

    lego.service.file:
        class:        Idk\LegoBundle\Service\FileManager
        arguments:    ["@service_container"]

    lego.service.log:
        class:        Idk\LegoBundle\Service\LogManager
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: log_manager, alias: log_manager }

    lego.security.password_encoder:
        class: "%lego.service.password_encoder.class%"



    lego.service.export:
        class:  '%lego.service.export.class%'
        arguments: ["@templating", "@lego.service.csv","@lego.service.meta_entity_manager"]
        public: true #https://stackoverflow.com/questions/49988904/symfony-how-to-call-private-services-in-bundle-controller

    Idk\LegoBundle\Service\Tag\ComponentChain:
        public: true #bootstraping service