parameters:
    lego.service.export.class: Idk\LegoBundle\Service\ExportService
    lego.service.menu.class: Idk\LegoBundle\Service\Menu
    lego.service.header.class: Idk\LegoBundle\Service\Header
    lego.service.meta_entity_manager.class: Idk\LegoBundle\Service\MetaEntityManager

services:

    lego.service.export:
        class:  '%lego.service.export.class%'
        arguments: ["@templating", "@lego.service.csv"]

    lego.service.menu:
        class:  '%lego.service.menu.class%'
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    lego.service.header:
        class:  '%lego.service.header.class%'
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    lego.service.meta_entity_manager:
        class:  '%lego.service.meta_entity_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]

    lego.twig.extension:
        class: Idk\LegoBundle\Twig\AdminListTwigExtension
        arguments: ["@service_container"]
        tags:
            -  { name: twig.extension }


    lego.twig.filter:
        class: Idk\LegoBundle\Twig\FilterTwigExtension
        tags:
            -  { name: twig.extension }

    lego.service.csv:
        class:        Idk\LegoBundle\Service\CsvManager
        arguments:    ["@doctrine.orm.entity_manager",";",'"']

    lego.service.file:
        class:        Idk\LegoBundle\Service\FileManager
        arguments:    ["@service_container"]

    lego.service.attachement:
        class:        Idk\LegoBundle\Service\AttachementManager
        arguments:    ["@service_container"]

    lego.service.log:
        class:        Idk\LegoBundle\Service\LogManager
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: log_manager, alias: log_manager } 


    lego.form.number:
        class: Idk\LegoBundle\Form\Type\NumberType
        tags:
            - { name: form.type, alias: lego_number }

    lego.form.color:
        class: Idk\LegoBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: lego_color }

    lego.form.role:
        class: Idk\LegoBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: lego_role }

    lego.form.geojson:
        class: Idk\LegoBundle\Form\Type\GeoJsonType
        tags:
            - { name: form.type, alias: lego_geojson }

    lego.form.latlng:
        class: Idk\LegoBundle\Form\Type\LatlngType
        tags:
            - { name: form.type, alias: lego_latlng }

    lego.form.markdown:
        class: Idk\LegoBundle\Form\Type\MarkdownType
        tags:
            - { name: form.type, alias: lego_markdown }

    lego.form.date:
        class: Idk\LegoBundle\Form\Type\DateType
        tags:
            - { name: form.type, alias: lego_date }

    lego.form.time:
        class: Idk\LegoBundle\Form\Type\TimeType
        tags:
            - { name: form.type, alias: lego_time }

    lego.form.auto_completion:
        class: Idk\LegoBundle\Form\Type\AutoCompletionType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lego_auto_completion }

    lego.form.datetime:
        class: Idk\LegoBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: lego_datetime }

    lego.form.dependent_select:
        class: Idk\LegoBundle\Form\Type\DependentSelectType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lego_dependent_select }

    lego.form.enity_hidden:
        class: Idk\LegoBundle\Form\Type\EntityHiddenType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lego_entity_hidden }


    lego.form.range:
        class: Idk\LegoBundle\Form\Type\RangeType
        tags:
            - { name: form.type, alias: lego_range }
