parameters:
    lle_adminlist.service.export.class: Idk\LegoBundle\Service\ExportService
    lego.service.menu.class: Idk\LegoBundle\Service\Menu
    lego.service.meta_entity_manager.class: Idk\LegoBundle\Service\MetaEntityManager

services:
    lle_adminlist.factory:
        class: Idk\LegoBundle\AdminList\AdminListFactory

    lle_adminlist.service.export:
        class:  '%lle_adminlist.service.export.class%'
        calls:
            -  [ setRenderer, [ "@templating" ] ]

    lego.service.menu:
        class:  '%lego.service.menu.class%'
        arguments: ["@doctrine.orm.entity_manager"]

    lego.service.meta_entity_manager:
        class:  '%lego.service.meta_entity_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]

    lle_adminlist.twig.extension:
        class: Idk\LegoBundle\Twig\AdminListTwigExtension
        arguments: ["@service_container"]
        tags:
            -  { name: twig.extension }


    lle_adminlist.twig.filter:
        class: Idk\LegoBundle\Twig\FilterTwigExtension
        tags:
            -  { name: twig.extension }

    lle_csv_manager:
        class:        Idk\LegoBundle\Service\CsvManager
        arguments:    ["@doctrine.orm.entity_manager",";",'"']

    lle_file_manager:
        class:        Idk\LegoBundle\Service\FileManager
        arguments:    ["@service_container"]

    lle_attachement_manager:
        class:        Idk\LegoBundle\Service\AttachementManager
        arguments:    ["@service_container"]

    log_manager:
        class:        Idk\LegoBundle\Service\LogManager
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: log_manager, alias: log_manager } 


    lle_adminlist.form.number:
        class: Idk\LegoBundle\Form\Type\NumberType
        tags:
            - { name: form.type, alias: lle_number }

    lle_adminlist.form.color:
        class: Idk\LegoBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: lle_color }

    lle_adminlist.form.role:
        class: Idk\LegoBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: lle_role }

    lle_adminlist.form.geojson:
        class: Idk\LegoBundle\Form\Type\GeoJsonType
        tags:
            - { name: form.type, alias: lle_geojson }

    lle_adminlist.form.latlng:
        class: Idk\LegoBundle\Form\Type\LatlngType
        tags:
            - { name: form.type, alias: lle_latlng }

    lle_adminlist.form.markdown:
        class: Idk\LegoBundle\Form\Type\MarkdownType
        tags:
            - { name: form.type, alias: lle_markdown }

    lle_adminlist.form.date:
        class: Idk\LegoBundle\Form\Type\DateType
        tags:
            - { name: form.type, alias: lle_date }

    lle_adminlist.form.time:
        class: Idk\LegoBundle\Form\Type\TimeType
        tags:
            - { name: form.type, alias: lle_time }

    lle_adminlist.form.auto_completion:
        class: Idk\LegoBundle\Form\Type\AutoCompletionType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lle_auto_completion }

    lle_adminlist.form.datetime:
        class: Idk\LegoBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: lle_datetime }

    lle_adminlist.form.dependent_select:
        class: Idk\LegoBundle\Form\Type\DependentSelectType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lle_dependent_select }

    lle_adminlist.form.enity_hidden:
        class: Idk\LegoBundle\Form\Type\EntityHiddenType
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: lle_entity_hidden }

    lle_adminlist.form.attribut_widget:
        class: Idk\LegoBundle\Form\Type\AttributWidgetType
        tags:
            - { name: form.type, alias: lle_attribut_widget }

    lle_adminlist.form.range:
        class: Idk\LegoBundle\Form\Type\RangeType
        tags:
            - { name: form.type, alias: lle_range }
