parameters:
    lego.service.export.class: Idk\LegoBundle\Service\ExportService
    lego.service.menu.class: Idk\LegoBundle\Service\Menu
    lego.service.header.class: Idk\LegoBundle\Service\Header
    lego.service.footer.class: Idk\LegoBundle\Service\Footer
    lego.service.meta_entity_manager.class: Idk\LegoBundle\Service\MetaEntityManager

services:

    lego.service.export:
        class:  '%lego.service.export.class%'
        arguments: ["@templating", "@lego.service.csv"]

    lego.service.menu:
        class:  '%lego.service.menu.class%'
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    lego.service.header:
        class:  '%lego.service.header.class%'
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    lego.service.footer:
        class:  '%lego.service.footer.class%'
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    lego.service.meta_entity_manager:
        class:  '%lego.service.meta_entity_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]

    lego.service.globals_parameters_provider:
            class: Idk\LegoBundle\Service\GlobalsParametersProvider
            arguments: ["%lego.skin%","%lego.layout%", "%lego.layout_login%"]

    lego.twig.extension:
        class: Idk\LegoBundle\Twig\LegoTwigExtension
        arguments: ["@service_container"]
        tags:
            -  { name: twig.extension }


    lego.twig.filter:
        class: Idk\LegoBundle\Twig\FilterTwigExtension
        tags:
            -  { name: twig.extension }

    lego.service.csv:
        class:        Idk\LegoBundle\Service\CsvManager
        arguments:    ["@doctrine.orm.entity_manager",";",'"']

    lego.service.file:
        class:        Idk\LegoBundle\Service\FileManager
        arguments:    ["@service_container"]

    lego.service.log:
        class:        Idk\LegoBundle\Service\LogManager
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: log_manager, alias: log_manager } 



