lego_index:
    path:      /lgo/{entity}
    defaults:
        _controller: lego.action.index

lego_add:
    path:      /lgo/{entity}/add
    defaults:
        _controller: lego.action.add

lego_component:
    path:      /lgo/{entity}/component/{cid}/{suffix_route}
    defaults:
        _controller: lego.action.component


lego_entity_reload:
    path:      /lgo/{entity}/entity/reload/{id}/{cid}/{suffix_route}
    defaults:
        _controller: lego.action.entityreload

lego_bulk:
    path:      /lgo/{entity}/bulk/{cid}/{ida}
    defaults:
        _controller: lego.action.bulk

lego_editinplace:
    path:      /lgo/{entity}/eip/{cid}/{suffix_route}
    defaults:
        _controller: lego.action.editinplace

lego_editinplaceentitychoice:
    path: /lgo/{entity}/eip/choice/{cid}/{suffix_route}
    defaults:
        _controller: lego.action.editinplaceentitychoice

lego_show:
    path:      /lgo/{entity}/{id}/show
    defaults:
        _controller: lego.action.show
    requirements:
        id: \d+

lego_delete:
    path:      /lgo/{entity}/{id}/delete
    defaults:
        _controller: lego.action.delete
    requirements:
        id: \d+

lego_edit:
    path:      /lgo/{entity}/{id}/edit
    defaults:
        _controller: lego.action.edit
    requirements:
        id: \d+

lego_export:
    path:      /lgo/{entity}/{cid}/{suffix_route}/export.{format}
    defaults:
        _controller: lego.action.export
        cid: 0

lego_sortcomponents:
    path:      /lgo/{entity}/sc/{suffix_route}
    defaults:
        _controller: lego.action.sort_components

lego_sortcomponentsreset:
    path:      /lgo/{entity}/screset/{suffix_route}
    defaults:
        _controller: lego.action.sort_components_reset

lego_autocompletion:
    path:      /lgo/{entity}/ac/{suffix_route}
    defaults:
        _controller: lego.action.autocompletion

lego_default:
    path:      /lgo/{entity}/{suffix_route}
    defaults:
        _controller: lego.action.default


idk_lego_widget_add:
    path:  /lgoint/widget/add
    defaults:
        _controller: lego.action.widget_add
idk_lego_widget_get:
    path:  /lgoint/widget/get/{widget}
    defaults:
        _controller: lego.action.widget_get


idk_lego_widget_save:
    path:  /lgoint/widget/save
    defaults:
        _controller: lego.action.widget_save

idk_lego_dashboard:
    path:  /dashboard
    defaults:
        _controller: lego.action.dashboard
